#!/usr/bin/env node

var cli = require('cli'),
	sys = require('sys'),
	fs = require('fs'),
	http = require('http'),
	options = cli.parse();

if(cli.args.length) {
	// We have a file
	filename = cli.args.shift();

	fs.readFile(filename, 'utf8', function(err, data){
		sendData(data);
	});
		
} else {
	// STDIN baby
	if(options.del) {
		console.log("delete!");
		sendData(" ");
	} else {
		cli.withStdin(function(d){
		sendData(d);
	});
	}
	
}

var sendData = function(data) {
	data = data || " " ;
	console.log("data");

	var method = 'POST';
	if(options.update) {
		method = 'PUT';
	} else if(options.del) {
		method = 'DELETE';
	}

	var http_options = {
		host: options.site || 'localhost',
		port: options.port || 3000,
		path: options.path || '/',
		method: method,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded'
		}
	};

	console.log(http_options);

	var req = http.request(http_options, function(res) {
		console.log('STATUS: ' + res.statusCode);
		console.log('HEADERS: ' + JSON.stringify(res.headers));
		res.setEncoding('utf8');
		res.on('data', function (chunk) {
			console.log('BODY: ' + chunk);
		});
	});

	// write data to request body
	req.write("post="+encodeURIComponent(data));
	req.end();
}





