#!/usr/bin/env node

var cli = require('cli'),
	sys = require('sys'),
	fs = require('fs'),
	http = require('http'),
	options = cli.parse();



if(cli.args.length) {
	// We have a file
	filename = cli.args.shift();

	

	fs.readFile(filename, 'utf8', function(err, data){
		sendData(data);

	});
} else {
	// STDIN baby
	cli.withStdin(function(d){
		sendData(d);
	});
}

var sendData = function(data) {
	var http_options = {
		host: 'localhost',
		port: 3000,
		path: '/',
		method: 'POST',
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded'
		}
	};

	var req = http.request(http_options, function(res) {
		console.log('STATUS: ' + res.statusCode);
		console.log('HEADERS: ' + JSON.stringify(res.headers));
		res.setEncoding('utf8');
		res.on('data', function (chunk) {
			console.log('BODY: ' + chunk);
		});
	});

	// write data to request body
	req.write("post="+encodeURIComponent(data));
	req.end();
}





